// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBizzCwM-b6am0TYHzvH1f3VWsKTztUSg',
    appId: '1:1095703403898:web:e9a2e360a15a1f540a0ac3',
    messagingSenderId: '1095703403898',
    projectId: 'ze-kinance',
    authDomain: 'ze-kinance.firebaseapp.com',
    storageBucket: 'ze-kinance.firebasestorage.app',
    measurementId: 'G-DEWJ0VBNDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADC_KAzYyWfI93-22UQ1DuH1ArCrLN6BQ',
    appId: '1:1095703403898:android:4347e00750a7f5ee0a0ac3',
    messagingSenderId: '1095703403898',
    projectId: 'ze-kinance',
    storageBucket: 'ze-kinance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtZcLjDqLw9vlEUFl48HhJiJqwliJCmNs',
    appId: '1:1095703403898:ios:c6b679912d47d7600a0ac3',
    messagingSenderId: '1095703403898',
    projectId: 'ze-kinance',
    storageBucket: 'ze-kinance.firebasestorage.app',
    iosBundleId: 'com.example.zekinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtZcLjDqLw9vlEUFl48HhJiJqwliJCmNs',
    appId: '1:1095703403898:ios:c6b679912d47d7600a0ac3',
    messagingSenderId: '1095703403898',
    projectId: 'ze-kinance',
    storageBucket: 'ze-kinance.firebasestorage.app',
    iosBundleId: 'com.example.zekinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBizzCwM-b6am0TYHzvH1f3VWsKTztUSg',
    appId: '1:1095703403898:web:fad13717db0b1bde0a0ac3',
    messagingSenderId: '1095703403898',
    projectId: 'ze-kinance',
    authDomain: 'ze-kinance.firebaseapp.com',
    storageBucket: 'ze-kinance.firebasestorage.app',
    measurementId: 'G-3QPR6GPK3J',
  );
}
